In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r"C:\Users\HP\OneDrive\Desktop\Cafe_Sales_CleanReport.xlsx")

In [4]:
df.head()

,Order_Id,Date,Time,Item,Category,Quantity,Unit_Price,Discount_%,Payment_Method,Salesperson,Total_Amount
0,ORD100101,2026-06-01,08:23,Espresso,Coffee,4,120,0,UPI,Arjun,480.0
1,ORD100102,2026-06-01,08:41,Cheesecake,Dessert,2,220,0,UPI,Riya,440.0
2,ORD100103,2026-06-01,10:03,Cappuccino,Coffee,4,180,0,Cash,Rahul,720.0
3,ORD100104,2026-06-01,10:10,Muffin,Bakery,2,110,10,Card,Neha,198.0
4,ORD100105,2026-06-01,10:19,Pasta,Food,4,280,0,Card,Rahul,1120.0

In [5]:
df.tail()

,Order_Id,Date,Time,Item,Category,Quantity,Unit_Price,Discount_%,Payment_Method,Salesperson,Total_Amount
1995,ORD102096,2026-06-30,19:42,Cheesecake,Dessert,2,220,0,Card,Arjun,440.0
1996,ORD102097,2026-06-30,20:15,Muffin,Bakery,2,110,0,Card,Riya,220.0
1997,ORD102098,2026-06-30,20:44,Cold Coffee,Coffee,2,240,0,UPI,Aman,480.0
1998,ORD102099,2026-06-30,21:05,Chicken Sandwich,Food,3,240,0,UPI,Priya,720.0
1999,ORD102100,2026-06-30,21:16,Latte,Coffee,2,200,5,Cash,Rahul,380.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_Id        2000 non-null   object
 1   Date            2000 non-null   object
 2   Time            2000 non-null   object
 3   Item            2000 non-null   object
 4   Category        2000 non-null   object
 5   Quantity        2000 non-null   int64
 6   Unit_Price      2000 non-null   int64
 7   Discount_%      2000 non-null   int64
 8   Payment_Method  2000 non-null   object
 9   Salesperson     2000 non-null   object
 10  Total_Amount    2000 non-null   float64
dtypes: float64(1), int64(3), object(7)
memory usage: 172.0+ KB

In [7]:
df.describe()

          Quantity   Unit_Price  Discount_%  Total_Amount
count  2000.000000  2000.000000  2000.00000   2000.000000
mean      2.514500   164.485000     4.95000    394.270500
std       1.106075    60.474485     5.80856    236.900424
min       1.000000    60.000000     0.00000     51.000000
25%       2.000000   110.000000     0.00000    200.000000
50%       3.000000   160.000000     0.00000    360.000000
75%       3.000000   220.000000    10.00000    540.000000
max       4.000000   280.000000    15.00000   1120.000000

In [8]:
df.isnull().sum()

Order_Id          0
Date              0
Time              0
Item              0
Category          0
Quantity          0
Unit_Price        0
Discount_%        0
Payment_Method    0
Salesperson       0
Total_Amount      0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dtypes

Order_Id           object
Date               object
Time               object
Item               object
Category           object
Quantity            int64
Unit_Price          int64
Discount_%          int64
Payment_Method     object
Salesperson        object
Total_Amount      float64
dtype: object

In [11]:
df.nunique()

Order_Id          2000
Date                30
Time               759
Item                18
Category             5
Quantity             4
Unit_Price          14
Discount_%           4
Payment_Method       3
Salesperson          6
Total_Amount       133
dtype: int64

In [12]:
df["Payment_Method"].value_counts()

Payment_Method
Card    676
Cash    666
UPI     658
Name: count, dtype: int64

In [13]:
df["Item"].value_counts()

Item
Cheesecake          131
Chicken Sandwich    131
Cold Coffee         131
Americano           128
Croissant           124
Latte               123
Veg Sandwich        120
Cookie              117
Espresso            109
Brownie             106
Green Tea           106
Iced Tea            103
Mocha               101
Cappuccino           99
Muffin               99
Pasta                97
Pizza Slice          95
Masala Tea           80
Name: count, dtype: int64

In [14]:
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Order_Id, Date, Time, Item, Category, Quantity, Unit_Price, Discount_%, Payment_Method, Salesperson, Total_Amount]
Index: []

In [15]:
df[df["Unit_Price"] > 1000]

Empty DataFrame
Columns: [Order_Id, Date, Time, Item, Category, Quantity, Unit_Price, Discount_%, Payment_Method, Salesperson, Total_Amount]
Index: []

In [17]:
df[df["Order_Id"].duplicated()]

Empty DataFrame
Columns: [Order_Id, Date, Time, Item, Category, Quantity, Unit_Price, Discount_%, Payment_Method, Salesperson, Total_Amount]
Index: []